### ISSUE TITLE
Laser energy is not recorded in summary or data files

### ISSUE THREAD

**Issue by ctdenney** [MalteWillmes/IsoFishR#9]
Laser energy is currently only recorded in the settings file, which has a single value of each parameter for a project. Laser energy occasionally changes for different slides or even individual otoliths within a project so it would be useful to record it at least in the summary file for each profile if not the individual data files.

**Comment by kransom14** [comment]
Hmm, I thought I put it in both files, my mistake. I will fix this today.

**Comment by MalteWillmes** [comment]
Yes basically laser energy should be recorded in the project settings file to set the default and then in the summary and individual data files. Maybe we should also move the laser energy input field, fluency, and spot size, to the "analysis tab" into the "Change inputs" box.

**Comment by kransom14** [comment]
I have corrected the laser energy issue and moved the energy, fluency, and spot size to the analysis tab within the change inputs box. Please close if looks good.

**Comment by MalteWillmes** [comment]
Looks great. Can you move "Sample type" as well. Apologies for not seeing this sooner.
